{% set name = "spyder-unittest" %}
{% set version = "0.4.1" %}
{% set hash = "41df85d84fb6ead35627befdc9aa57c15b96b3558aff51731c0ffb1c1fac0e9e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - lxml
    - python
    - spyder >=4,<5
    - pyzmq

test:
  imports:
    - spyder_unittest

about:
  home: https://github.com/spyder-ide/spyder-unittest
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder plugin that integrates popular unit test frameworks.
  description: |
    It allows you to run tests and view the results.
  dev_url: https://github.com/spyder-ide/spyder-unittest

extra:
  recipe-maintainers:
    - ccordoba12
    - jitseniesen
    - goanpeca
