{% set name = "spyder-unittest" %}
{% set version = "0.4.0" %}
{% set hash_type = "sha256" %}
{% set hash = "f48894d7b31255f4f2b195236d99abc800e74fd768222862ed188653e2321273" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - lxml
    - python
    - spyder >=3
    - pyzmq

test:
  imports:
    - spyder_unittest

about:
  home: https://github.com/spyder-ide/spyder-unittest
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder plugin that integrates popular unit test frameworks.
  description: |
    It allows you to run tests and view the results.
  dev_url: https://github.com/spyder-ide/spyder-unittest

extra:
  recipe-maintainers:
    - ccordoba12
    - jitseniesen
    - goanpeca
