travis:
  secure:
    BINSTAR_TOKEN: cAQsHBxzPOkHkJ4dFfkS8vZxTCRaL7QdEqlMkEnerQLDtl09+2Iu1rxiVY98ivv+j3ViHswB8OvJBfbpL1PaJoP9DrqXnihYwRWC7rvgKasWLKhdmezKd4CPn7rHi9WBnok0hiuw6sAvVgGDkHfwcRxWbvDyQ7tJ4PXZCgFA5M9JZr7jAN7RpgkNJgbalRk01i+jQJogCMOTB+8BuGT0XF7PyrEyyfaqmVnsyunukVBoaVaIcmvsvg936w0KDFTvB+P/LYWqjxflfkqFyyReGotD8HVIiTP/diQsu6WnAkzO8/N/k1rZDp8u7fZE3H7ysaeYmVoP42tNmj4vUrJGsAW1XyLfnF2T57ujkrAr8O9iTqHVQmggC2+/5uNWql0Bnw0sqDHihyoontUh8PANkNOdnUeHxi7LwqMFia79b4Zcqr3UKb4BLIxcJFIVzkPQ7gvOUH4uSa2EooYqYA87otw4Q0rjQfNfJ+K1QM29lXgf9BXkwOCrIeFWX7lBvINsrLQ5p/ZQ4KI41VlfnlsCXSn70Fc1XQMW2hH8SXNR53m/MpD1fQm+RGpAvPFh9ZFCQcHBJJi6JjSlzJ3WO31GpKQehvX0O7pAvOu92IaovhsnUQDmiUrUFl11dbiuGhj5fLJ92hMwJeMhkF8vP5CqDTXjcjyIjLjfh1dOZLx2EcI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
