travis:
  secure:
    BINSTAR_TOKEN: Nay+R1SDd6Dd8co88Ia67UKupUNWjEye6F/BkQ0mJBc011xnr3aBX6A5BJuX3bwfyTHxggwlDoWv8sXlNRiDtmgOpTdbFMlHGNSSLjVXZRh/FXbeSsHDoQ1D+T9NwMiQXTNFZGzU5bmX/AfI65HaZVZv6Oj4QEqIQBGk/hzwPUNtz+FQki7NDRIR555i1kfSPYU8Abf9ZG+9Ju7X1n2ya2irviXca3Z0sdHhLYLRAIB9MoiKdz/+R+La0103rxhPNmeVDI9rt8Vz27DCnk4P94/uddHrW2yMVmSrMpPkKVcsT7oX6TzITOVLQcytED+JPP1sQHu1F6bfMetGExjwjCYP/cfkstT//kEuXhlBSklvEJEMm8aoUPC83X7R+y288MXYmU9QHPimPguZ8e2AdKZ3uq27DTzfdUfem6lw9odBKtkpVHX3Jx4aZJj0BcNyRhCG4ODO5rsuSFF3d8nqMqJWTCu5UrjEo3M3JfXRA+s0rl/d6cKN5PNPn+wtkpBXlhmJQge2zXxzJXSWowJH3ECgIPROoLWYVs+ku4SL3vHObItE0bnkXiKoLND0EVXBZfdgeJkPbOLC/mIUQOuha7EyRCyrneybGMkV5nnbAhu0LuT3cCTIIxfy0enNjsB6J5LOc5BZ3+4JVFuCmdj66Kd1OjkwHvLO1gcQuOnOQM8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
